# Creacion de Matrices 

In [3]:
import numpy as np

In [4]:
m = np.array([[1,2,3],
              [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [7]:
a = np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
f = np.full((5,3),8)
print(f)

[[8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]
 [8 8 8]]


In [9]:
x = np.random.randint(1,10,(3,3))
print(x)

[[3 7 9]
 [6 4 7]
 [9 8 4]]


In [11]:
c = np.eye(10)
print(c)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [ ]:
k = np.arange(12)
print(k)

print(k.reshape((3,4))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
